### PR TITLE
feat: upgrade to Angular 13 and support modern package format

### PR DESCRIPTION
**Pull request by arturovt**

### CODE REVIEW

**Comment by arturovt** [comment]
I cherry picked from 8d3da96d4c7cede4a0f3750ecd2dada6cc4618a5. @shhdharmen can you create a beta branch?

**Comment by shhdharmen** [comment]
@arturovt done

**Comment by arturovt** [comment]
I've changed the base.

**Review by shhdharmen — APPROVED** [review]
LGTM

**Pull request merged**
