### PR TITLE
fix: reference namespace explicitly

### PR DESCRIPTION
**Pull request by arturovt**

### CODE REVIEW

**Comment by arturovt** [comment]
Started testing beta package within the ng13 playground and it throws ` Cannot find namespace 'Inputmask'.` since it's not imported explicitly.

**Comment by shhdharmen** [comment]
LGTM. @arturovt You can also test this library locally in following way:

1. `npm run build:lib`
2. `cd dist/ngneat/input-mask`
3. `npm pack`
4. Above will generate `ngneat-input-mask-0.0.0.tgz` in `dist/ngneat/input-mask`
4. `cd /path/to/your/ng/13/project/`
5. `ng add /path/to/dist/ngneat/input-mask/ngneat-input-mask-0.0.0.tgz`
6. Check

Let me know once you have tested in above way and want me to merge.

I think I should also figure out how to test above scenario 😅.

**Comment by arturovt** [comment]
@shhdharmen done, went well.

**Pull request merged**
